parameters:
#    simple_task.example.class: Simple\TaskBundle\Example

services:
#    simple_task.example:
#        class: %simple_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
