Simple\TaskBundle\Entity\Osoba:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
        surname:
            - NotBlank: ~
            - Length:
                max: 3
        phone:
            - NotBlank: ~
        address:
            - NotBlank: ~
        email:
            - NotBlank: ~