simple_task:
    resource: "@SimpleTaskBundle/Resources/config/routing.yml"
    prefix:   /

simple_profile:
    resource: "@SimpleProfileBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
acme_website:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix: /

# src/Acme/DemoBundle/Resources/config/routing.yml
random:
    path: /random/{limit}
    defaults: { _controller: AcmeDemoBundle:Random:index }

profil:
    path: /profil/
    defaults: { _controller: SimpleProfileBundle:Default:index }

profil_dodaj:
    path: /profil/dodaj/
    defaults: { _controller: SimpleProfileBundle:Osoba:new }

profil_ispis:
    path: /profil/ispis/
    defaults: { _controller: SimpleProfileBundle:Osoba:index }

profil_upisi:
    path: /
    defaults: { _controller: SimpleProfileBundle:Osoba:create }

profil_pregled:
    path: /profil/pregled/{id}
    defaults: { _controller: SimpleProfileBundle:Osoba:show }

profil_uredi:
    path: /profil/uredi/{id}
    defaults: { _controller: SimpleProfileBundle:Osoba:edit }

profil_azuriraj:
    path: /profil/azuriraj/{id}
    defaults: { _controller: SimpleProfileBundle:Osoba:update }

profil_brisi:
    path: /profil/brisi/{id}
    defaults: { _controller: SimpleProfileBundle:Osoba:delete }